from .vulnerability_opencti import VulnerabilityOpenCTIPropertiesExtension
from .vulnerability_scoring import VulnerabilityScoringExtension
from .software_cpe_properties import SoftwareCpePropertiesExtension
from .report_epss_scoring import ReportEPSSScoring
from .location_opencti import LocationOpenCTIPropertyExtension
from .indicators_vulnerable_cpe import IndicatorVulnerableCPEPropertyExtension
from .indicator_sigma_rule import IndicatorSigmaRulePropertyExtension
from .identity_opencti import IdentityOpenCTIPropertyExtension  